name: Docker CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Clean and Build
        run: |
          mvn clean,
          mvn package -DskipTests
