name: Docker CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Clean
        run: mvn clean
      - name: Build Jar   
        run: mvn package -DskipTests
