name: Docker CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Leadiro Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13  
      - name: Maven clean
        run: mvn clean
      - name: Maven package   
        run: mvn package -DskipTests
      - name: Docker login
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER --password-stdin $DOCKER_PASSWORD
      - name: Build docker image
        run: docker build -t leadiro-project-delwynb .
      - name: Push docker image
        run: docker push leadiro-project-delwynb
      
