name: Docker CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13  
      - name: Maven Clean
        run: mvn clean
      - name: Maven Package   
        run: mvn package -DskipTests
      - name: Build Docker Image
        run: docker build -t leadiro-project-delwynb .
